[v1]
"wasm-bindgen-cli 0.2.125 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen-test-runner.exe",
    "wasm-bindgen.exe",
    "wasm2es6js.exe",
]
"wasm-server-runner 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-server-runner.exe"]
